apiVersion: v1
kind: Pod
metadata:
  name: ml
spec:
  containers:
  - image: lisker/ml-docker:latest
    name: ml-2
    env:
    - name: data_path
      value: "http://43.143.180.76/playlist-sample-ds2.csv"
    volumeMounts:
    - name: project2-pv-yg202
      mountPath: /app/data
  restartPolicy: OnFailure
  volumes:
      - name: project2-pv-yg202
        persistentVolumeClaim:
          claimName: project2-pv-yg202
